prompt_templates = {
    'en' : {
        'first_sentence' : "The task is to label all mentions of {} in a sentence. {} I can also put them in a specific format. Here are some examples of sentences I can handle:\n",
        'last_sentence' : "Imitate me. Identify all the mentions of {} in the following sentence, by putting \"{}\" in front and a \"{}\" behind each of them.\n",
        'ner_tags_plural' : {
            'PER' : "person names",
            'DISO' : "disorders",
            'LOC' : "places",
            'ORG' : "organizations",
            'ANAT' : "parts of the body",
            "LIVB" : "living beings",
            "PROC" : "procedures",
            "FAC" : "facilities",
            "CHEM" : "chemicals",
            "DEVI" : "medical devices",
            "GEOG" : "geographical zones",
            "OBJC" : "non-medical objects",
            "PHEN" : "physiolocal phenomema",
            "PHYS" : "human physiology",
            "ACTI" : "activities",
            "CONC" : "concepts",
            },
        'ner_tags' : {
            'PER' : "a person's name",
            'DISO' : "an alteration of the functions of the body",
            'LOC' : "a place",
            'ORG' : "an organization",
            'ANAT' : "a part of the body",
            "LIVB" : "a living being",
            "PROC" : "a procedure",
            "FAC" : "a facility",
            "CHEM" : "a chemical",
            "DEVI" : "a medical device",
            "GEOG" : "a geographical zone",
            "OBJC" : "a non-medical object",
            "PHEN" : "a physiolocal phenomemon",
            "PHYS" : "a human physiology",
            "ACTI" : "an activity",
            "CONC" : "a concept",
            },
        'ner_tags_description' : {
            'PER' : "These are words that refer to the name of a real or fictional person.",
            'DISO' : "These are words that refer to an alteration or abnormality of the functions or health of the body.",
            'LOC' : "These are words that refer to the name of a place.",
            'ORG' : "These are words that refer to the name of an organization.",
            'ANAT' : "These are words that refer to a part of the human body.",
            "LIVB" : "These are words that refer to a living being.",
            "PROC" : "These are words that refer to a medical procedure.",
            "FAC" : "These are words that refer to a facility made by humans.",
            "CHEM" : "These are words that refer to a drug or a chemical substance.",
            "DEVI" : "These are words that refer to a medical device or a medical instrument.",
            "GEOG" : "These are words that refer to a geographical zone.",
            "OBJC" : "These are words that refer to an object that is not necessarily medical.",
            "PHEN" : "These are words that refer to a physiolocal phenomemon or a physiolocal function.",
            "PHYS" : "These are words that refer to a human physiology.",
            "ACTI" : "These are words that refer to an activity.",
            "CONC" : "These are words that refer to a medical concept.",
            },
        'input_intro' : "Input: ",
        'output_intro' : "Output: ",
        'first_sentence_self_verif' : "The task is to verify whether a given word is a mention of a {}. {} Here are some examples:\n",
        "self_verif_template": "In the sentence \"{{sentence}}\", is \"{{word}}\" {ner_tag}?\n",
        "yes": "Yes",
        "no": "No",
        }
    ,
    # 'vicuna_assistant' : {
    #     'first_sentence' : "A chat between a curious {} and an artificial intelligence assistant. The assistant can label all mentions of {} in a sentence. {} It can also put them in a specific format. Here are some examples of sentences it can handle:\n",
    #     'last_sentence' : "",
    #     'ner_tags_plural' : {
    #         'PER' : "person names",
    #         'DISO' : "disorders",
    #         'LOC' : "places",
    #         'ORG' : "organizations",
    #         'ANAT' : "parts of the body",
    #         'LIVB' : "living beings",
    #         'PROC' : "procedures",
    #         },
    #     'ner_tags' : {
    #         'PER' : "a person's name",
    #         'DISO' : "an alteration of the functions of the body",
    #         'LOC' : "a place",
    #         'ORG' : "an organization",
    #         'ANAT' : "a part of the body",
    #         'LIVB' : "a living being",
    #         'PROC' : "a procedure",
    #         },
    #     'ner_tags_description' : {
    #         'PER' : "These are words that refer to the name of a real or fictional person.",
    #         'DISO' : "These are words that refer to an alteration or abnormality of the functions or health of the body.",
    #         'LOC' : "These are words that refer to the name of a place.",
    #         'ORG' : "These are words that refer to the name of an organization.",
    #         'ANAT' : "These are words that refer to a part of the human body.",
    #         'LIVB' : "These are words that refer to a living being.",
    #         'PROC' : "These are words that refer to a medical procedure.",
    #         },
    #         'input_intro' : "USER : ",
    #         'output_intro' : "ASSISTANT : ",
    #         'first_sentence_self_verif' : "A chat between a curious {} and an artificial intelligence assistant. The assistant can verify whether a given word is a mention of a {}. Below some examples :\n",
    #         "self_verif_template": "USER : In the sentence \"{sentence}\", is \"{{word}}\" {ner_tag}?\n",
    #         "yes": "ASSISTANT : Yes",
    #         "no": "ASSISTANT : No",
    # },
    'fr' : {
        'first_sentence' : "La tâche est d'identifier toutes les mentions de {} dans une phrase. {} Il faut aussi les mettre en forme. Voici quelques exemples :\n",
        'last_sentence' : "Imite-moi. Identifie les mentions de {} dans la phrase suivante, en mettant \"{}\" devant et un \"{}\" derrière la mention dans la phrase suivante.\n",
        'ner_tags_plural' : {
            'PER' : "noms de personnes",
            'DISO' : "maladies et symptômes",
            'LOC' : "lieux",
            'ORG' : "organisations",
            'ANAT' : "parties du corps",
            'LIVB' : "êtres vivants",
            'PROC' : "procédures médicales",
            "FAC" : "installations",
            "CHEM" : "substances chimiques",
            "DEVI" : "appareils médicaux",
            "GEOG" : "zones géographiques",
            "OBJC" : "objets non médicaux",
            "PHEN" : "phénomènes physiologiques",
            "PHYS" : "physiologie humaine",
        },
        'ner_tags' : {
            'PER' : "un nom de personne",
            'DISO' : "une altération des fonctions du corps",
            'LOC' : "lieu",
            'ORG' : "une organisation",
            'ANAT' : "une partie du corps",
            'LIVB' : "un être vivant",
            'PROC' : "une procédure médicale",
            "FAC" : "une installation",
            "CHEM" : "une substance chimique",
            "DEVI" : "un appareil médical",
            "GEOG" : "une zone géographique",
            "OBJC" : "un objet non médical",
            "PHEN" : "un phénomène physiologique",
            "PHYS" : "une physiologie humaine",
        },
        'ner_tags_description' : {
            'PER' : "Il s'agit des mots faisant mention du nom d'un personne qu'elle soit réelle ou fictive.",
            'DISO' : "Il s'agit des mots faisant mention d'une altération ou une anormalité des fonctions ou de la santé du corps.",
            'LOC' : "Il s'agit des mots faisant mention du nom d'un lieu.",
            'ORG' : "Il s'agit des mots faisant mention du nom d'une organisation.",
            'ANAT' : "Il s'agit des mots faisant mention d'une partie du corps humain.",
            'LIVB' : "Il s'agit des mots faisant mention d'un être vivant.",
            'PROC' : "Il s'agit des mots faisant mention d'une procédure médicale.",
            "FAC" : "Il s'agit des mots faisant mention d'une installation faite/construite par les humains.",
            "CHEM" : "Il s'agit des mots faisant mention d'un médicament ou d'une substance chimique.",
            "DEVI" : "Il s'agit des mots faisant mention d'un appareil médical ou d'un instrument médical.",
            "GEOG" : "Il s'agit des mots faisant mention d'une zone géographique.",
            "OBJC" : "Il s'agit des mots faisant mention d'un objet qui n'est pas nécessairement médical.",
            "PHEN" : "Il s'agit des mots faisant mention d'un phénomène physiologique ou d'une fonction physiologique.",
            "PHYS" : "Il s'agit des mots faisant mention d'une physiologie humaine.",
        },
        'input_intro' : "Entrée : ",
        'output_intro' : "Sortie : ",
        "first_sentence_self_verif" : "La tâche est de vérifier si un mot est une mention des {} dans une phrase. {} Voici quelques exemples :\n",
        "self_verif_template": "Dans la phrase \"{{sentence}}\", le mot \"{{word}}\" désigne-t-il {ner_tag} ?\n",
        "yes": "Oui",
        "no": "Non",
    }
}